### ISSUE TITLE
get_bucket_version2をコールするとParamValidationErrorになる

### ISSUE THREAD

**Issue by kakakikikeke** [nifcloud/nifcloud-sdk-python#100]
バージョン1.3.0
Python 3.10.2

サンプルコード

```
from nifcloud import session

client = session.get_session().create_client(
    "storage",
    region_name="jp-east-1",
    endpoint_url="https://jp-east-1.storage.api.nifcloud.com",
    nifcloud_access_key_id="xxx",
    nifcloud_secret_access_key="xxx",
)

result = client.get_bucket_version2(
    Bucket='bucket1'
)

print(result)
```

エラー内容

```
Traceback (most recent call last):
  File "/root/work/nifcloud_storage/test.py", line 17, in <module>
    result = client.get_bucket_version2(
  File "/root/.local/share/virtualenvs/nifcloud_storage-pwINQavl/lib/python3.10/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/root/.local/share/virtualenvs/nifcloud_storage-pwINQavl/lib/python3.10/site-packages/botocore/client.py", line 677, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/root/.local/share/virtualenvs/nifcloud_storage-pwINQavl/lib/python3.10/site-packages/botocore/client.py", line 725, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/root/.local/share/virtualenvs/nifcloud_storage-pwINQavl/lib/python3.10/site-packages/botocore/validate.py", line 337, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Missing required parameter in input: "ListType"
```

get_bucket は問題ないようです、ただ非推奨っぽいので get_bucket_version2 を使えるようにしていただけると助かります。

**Comment by aokumasan** [comment]
Hi @kakakikikeke, `GetBucketVersion2` API requires the parameter `list-type`. (Please see https://pfs.nifcloud.com/api/object-storage-service/GetBucketVersion2.htm)

So you should add the parameter `ListType` to your code.
```python
result = client.get_bucket_version2(
    Bucket="bucket1",
    ListType="2"
)
```

**Comment by kakakikikeke** [comment]
ありがとうございます。コールできました。
